### ISSUE TITLE
!aegis removing recent manual permaban

### ISSUE THREAD

**Issue by Lemmiiwinks** [destinygg/chat-bot#107]
This happened in twitch chat a while ago (Feb 28th UTC), But !aegis appeared to unban a recent, manually perma banned chatter.

Relevant logs:
> [01:07:45]  zadeh: @Destiny Maybe she does not want to break the session? you dumbfuck LULW
> [01:07:58] destiny banned zadeh

> [01:46:18]  loomies: !nuke 10m youtube
> [01:47:58]  loomies: !aegis
> [01:48:03] destinyggbot unbanned zadeh

Some notes:
The user didn't appear to have said "youtube" in their previous logs that day
Aegis unban event was 40 minutes after the manual perma ban by destiny

![image](https://user-images.githubusercontent.com/68769092/133931110-409182fd-2b08-462a-bb23-55381ea57b98.png)
*Viewer card times in CST

This doesn't seem like intended behavior unless we've overlooked something else that would've prompted the save by aegis.

Initially caught by EMPIREF4N.

**Comment by shadedred** [comment]
heh, a year later, THIS IS FIXED :feelsgood:
