### ISSUE TITLE
stacking mutes

### ISSUE THREAD

**Issue by caneut** [destinygg/chat-bot#30]
mutes stacks for things that might be accidental, which is ok

mutes do not stack for the mute caused by saying the n slur, which is 99% of cases is not accidental.

This isn't very logical.

**Comment by linusred** [comment]
The problem with this for me, is that banned phrase can vary in length from 10 minutes to literally days. So the severity of it could jump wildly.

If someone is repeatedly using the nword, they should be able to be manually moderated quite easily.
