### ISSUE TITLE
New Feature: Anti-Linker Mode

### ISSUE THREAD

**Issue by ILiedAboutCake** [destinygg/chat-bot#62]
A new feature mode should include a command-togglable to mute links in the chat. Mute should be 10 minutes,

The command should be a bool toggle, same to enable and disable.(`!mutelinks on`/`!mutelinks off`).

If you're feeling adventurous, you could make it act similar to a nuke, but only for links. (`!mutelinks on 1h`)

When enabled: all hyperlinks in chat are 10 minute muted. Hyperlinks in chat are valid without http(s):// in the URL. 

![image](https://user-images.githubusercontent.com/7504947/95255330-31433b80-07ef-11eb-985c-2978441791b7.png)

**Comment by johnpyp** [comment]
I'll try to do this tonight.

**Comment by ILiedAboutCake** [comment]
The original scope, requested by Destiny. `Ability to turn off link mode in chat, if anyone mentions my name + has a link, they are auto-muted for 10 minutes, this is hopefully easy to implement via the bot.` 

I think there should be multiple modes to this, because we know how this works with chat. 

1. Chat will spam links
2. Destiny will mute links at him
3. Chat will keep posting links indirectly, and Destiny will click them.
4. Meganukes 😔 

Instead of meganukes, the bot should offer multiple stages:

1. Mute no links `!mutelinks off`
2. Mute links posted + x in the string (x where invoker) `!mutelinks (destiny|on)` where on = invoker
3. Mute ALL links posted `!mutelinks all`
