### ISSUE TITLE
Bot is in UTC Time

### ISSUE THREAD

**Issue by staymadson** [destinygg/chat-bot#69]
When you are banned and refresh the page for the first time, the bot displays the ban time in UTC and, if the difference between your local date and UTC date is different, will say "tomorrow" instead of today for short length bans.

Visual screen shot of error: https://i.imgur.com/0uUcIxX.png

Reproduction steps:

1. Get banned for a short period of time.
2. Refresh the chat once.
 
Note the error goes away if you refresh more than once

Bonus meme:

████████▓▓████████▓▓█████████████
██████▓▓█████████████▓███████████
█████▓███████████████▓███████████
████▓█████████████████▒██████████
████▓▓▓▒░░▒▒▒▒▒▒▒▒▒▒▒▒▒██████████
████▒▒░▒▒░▒▒▗▒▒▒▒▒▒▗▒▒▒██████████
████▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██████████
████░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█████████
█████▒▒▒▒▒▒▒▒▃▒░░░▒▃▒▒███████████
██████▓▒▒▒▒▒▃▒▒▒▒▒▒▒▃░▒▒█████████
███████▒▒▒▒░▒▒▒▒▒▒▒▒▒▒░██████████
█████████▒░░░░░░░░░░░░░██████████
██████████░▒░░░░░░░░░░██▓▒▒▒▒▒▓▒▓
▓▓█████████████▒░░░▒████▒▒▒▒▒▓▓▒▓
▒▒▒▒▒▒▓███████████████████▒░░▒▒▒█
▒▒▒▒▒▓▓▒▒█████████████▒████░▒████
█▒▒▒▓▓▒▒▒████████████▒███████████
███▓▒▓▓▒█████████████████████████
░░█▀▀░░█▄░█░█▀▀█░█▄░▄█░█▀▀░█▀▄
░░█░▀█░█░▀█░█░░█░█░▀░█░█▀▀░█░█
░░▀▀▀░░▀░░▀░▀▀▀▀░▀░░░▀░▀▀▀░▀▀░

**Comment by shadedred** [comment]
Thanks for reporting! This is a website issue, rather than a bot issue, so feel free to move the issue there, gunna close this one up though.

**Comment by shadedred** [comment]
https://github.com/destinygg/website
