### ISSUE TITLE
!addban functionality in twitch

### ISSUE THREAD

**Issue by Lemmiiwinks** [destinygg/chat-bot#87]
When !addban is used in twitch or dgg it results in permanent bans for users in twitch chat regardless of the time specified.

This happens because there is no such thing as a timed ban in twitch chat. All timed events are timeouts and have a max of 2 weeks.

!addban should be updated to issue timeouts (instead of bans) in twitch chat
OR
if !addban isn't all that important.... !addban could just be added as an alias for the !addmute command.

OOOO

**Comment by shadedred** [comment]
So bans stop a user from using the chat entirely. Timeouts just stop them from posting. If the intention is to ban a user, muting isn't the same.

Bans are permanent in twitch though, so I dunno. Maybe just consider all bans permanent in twitch?

**Comment by Lemmiiwinks** [comment]
Yeah I understand that there is a difference.

!addban works perfectly fine in dgg, No issues there.

but if you do an !addban 30m .. it will be working fine as intended for dgg.. but in twitch anyone using the banned phrase will be permanently banned, this isn't in line with the original intention of the command. The original intent would be limiting the users interaction with chat for 30m for using the phrase. Not permanently banning them.


The way it works now, me or rtba or whoever just ends up changing them all to addmutes anyways to avoid the issue.

**Comment by shadedred** [comment]
If that's what you want, we can do that, and keep ipban as the big permanent real ban.

**Comment by Lemmiiwinks** [comment]
Ok so after testing and revisiting this one maybe it's better if I describe the scenario we're trying to avoid.

Streamer man doesn't want to talk about AOC.
Streamer man types "!addban 30m AOC" into DGG chat.

"AOC" is added to the ban list for both twitch and DGG, since the list is shared.

Someone in DGG types "AOC" < ------ The user is banned for 30m.
Someone in Twitch types "AOC" < ------ The user is banned permanently instead of the 30m penalty intended.

The ban/mute list is shared so regardless of where the "!addban" command is issued we need it to register as a mute (or at least carry out a mute separately for twitch chat) so twitch doesn't get fucked.

I believe the last solution only affected when !addban was typed into twitch chat. So if !addban is used in DGG then twitch chatters still get fucked, which was the issue we're trying to solve.

**Comment by johnpyp** [comment]
What if in the twitch chat module, if a duration is provided, just change the "ban" to a mute with the same parameters?

**Comment by Lemmiiwinks** [comment]
The default duration is 30m if no duration is provided. So, I'm not sure it should rely only on a duration being provided... but maybe you count no duration as the default duration being applied 🤷

**Comment by johnpyp** [comment]
Are bans only permanent when "perm" is explicitly provided? In otherwords, can we just treat every "ban" that isn't explicitly permanent as a mute with that duration?

**Comment by Lemmiiwinks** [comment]
I can't say I've ever seen an !addban used to permanently ban anyone. I imagine if it was it would need "perm" or "0" or something specific like you said.

**Comment by Lemmiiwinks** [comment]
4:35:23Destiny: !ban blunaluna123
destinyggbot timed out blunaluna123 for 600 seconds. Reason: blunaluna123 banned through bot by destiny. .

https://i.imgur.com/lu85hSk.png

So we may have broke this use case which should probably still result in a perma.

This should probably be double checked. But the default time for an '!addban' is 10m (Which was the original issue we were fixing) but the default duration for a normal "!ban" i THINK is permanent. [citation needed]


ALSO
!meganuke without a duration isn't permabanning in twitch chat, I'm not sure if meganuke changed from the original issue which said it should default to permas 🤷 when used in dgg it looks like default is timed. (So this may or may not be related to issue above)

**Comment by shadedred** [comment]
only !ipban defaults perm. !ban has always defaulted to 10 minutes, this is the behavior on DGG and always has been.

!meganuke doesn't permaban without a duration. 

There is no issue here.
