### ISSUE TITLE
Reimplement !live command for YouTube using the Live Streaming API

### ISSUE THREAD

**Issue by dotted** [destinygg/chat-bot#91]
Currently the YouTube Data API is used to grab the livestream video ID to get the concurrent viewer count off youtube, however the quota cost of doing this is very high (100 points, of the 10000 daily allotment) even if you are using etags, as they are seemingly ignored in terms of quota cost for searches effectively making #90 entirely useless.

Now we can [do some caching](https://github.com/destinygg/chat-bot/compare/master...dotted:this-is-what-peak-youtube-performance-looks-like) which prevents a lot of search api calls when the broadcast is live, which would no doubt actually reduce the API usage quite dramatically. However it does nothing if there is no stream, therefore each !live command invocation will incur the the 100 point quota cost. We could get creative and instead of doing the search we could probably check the X number of latest videos for liveStreamingDetails and if they dont have a live viewer count assume there is not stream. Alternatively assume there is never a YouTube stream without a Twitch stream and only perform the search api call on youtube if there is an active twitch stream, but that that excludes !live from working if Destiny is talking to a person banned on twitch ie. Vaush.

So the real solution is to use the YouTube Live Streaming API instead, which I'd be happy to do however that will require OAuth tokens to Destiny's channel to make it work in production.

GOOD LUCK!

**Comment by hayksaakian** [comment]
If you're added as a manager or something on the youtube channel would it work?

This is personally frustrating to me as a viewer so I'm willing to code a solution that just scrapes the youtube page for this info too. 

I have enough access to proxies  to fully sustain 1 request per minute every month no problem. 

Happy to submit a PR if scraping would be acceptable.
