### ISSUE TITLE
The app closed itself cause of some triple fonctions

### ISSUE THREAD

**Issue by Itzkizzmo** [destinygg/chat-bot#92]
lines {265,160}
contact me on instagram : ikzmoo

**Comment by ILiedAboutCake** [comment]
Please provide a stack trace of the errors or steps to reproduce your bug.

**Comment by shadedred** [comment]
If you're trying to run the bot yourself, you're just missing configuration. Refer to the sample configuration or disable the registration of commands that use specific API keys.
