### ISSUE TITLE
Documentation improvements to help contributors get their local environment set up

### ISSUE THREAD

**Issue by hayksaakian** [destinygg/chat-bot#96]
List of notes to improve readme for first time setup (will be editing this issue as I find more improvements)

create an empty file named bot.db and mention that location in the config prod.config.json file

Code updates:
update sample.config.json to mention redditVote

Not sure if this a version specific thing for node js:
change
```
const { readFile, writeFile } = require('fs/promises');
```
to
```
const { readFile, writeFile } = require('fs').promises;
```

**Comment by dotted** [comment]
> Not sure if this a version specific thing for node js:

The bot runs on Nodejs 14, and `const { readFile, writeFile } = require('fs/promises');` works on 14.

**Comment by hayksaakian** [comment]
must be on my end, for some reason my system is running it with 13.9.0
